version: 0.0
os: linux
files:
 - source: /
   destination: /home/ec2-user/kafe-app
permissions:
  - object: /home/ec2-user/kafe-app/Service/Controllers/app.py
    owner: ec2-user
    mode: 644
    type:
      - file
  - object: /home/ec2-user/kafe-app/Service/main.py
    owner: ec2-user
    mode: 644
    type:
      - file
  - object: /home/ec2-user/kafe-app/requirements.txt
    owner: ec2-user
    mode: 644
    type:
      - file
  - object: /home/ec2-user/kafe-app/supervisord.conf
    owner: ec2-user
    mode: 644
    type:
      - file
hooks:
  BeforeInstall:
   - location: scripts/delete_app
     timeout: 300
     runas: root
  AfterInstall:
   - location: scripts/install_app_dependencies
     timeout: 300
     runas: root
  ApplicationStart:
   - location: scripts/start_server
     timeout: 300
     runas: root